### ISSUE TITLE
Noise reduction

### ISSUE THREAD

**Issue by daveabiy** [XYangXRay/ganrec#7]
The current status is PSNR value of about 29. Which is still very noisy. How did you solve it?

Note: Approaches can be:

> 1. filter function through every iteration
> 2. filter at only the end
> 3. introducing another filtering block
> 4. Fourier transforming the image and it's retrieved and do an error function
> 5.  ...

**Comment by daveabiy** [comment]
@XYangXRay , @moosmann , @kulvait 

Hi Xiaogang, 

Can you send me the parameters you used for your reconstruction of the spider hair?

Kind regards,

**Comment by XYangXRay** [comment]
https://github.com/XYangXRay/ganrec/blob/develop/ganrec/tests/phase_spider_20221020.py
The parameters are as in the script above. I downsampled the data to 512*512 for this case.
