### ISSUE TITLE
explanation with the read file

### ISSUE THREAD

**Issue by daveabiy** [XYangXRay/ganrec#8]
Hi @XYangXRay ,

On the spider test python file, the way the reading was added is a bit confusing. can you please help me understand it better?

```
    fname_data = '/data/gan_phase/data_spider.tif'
    data = dxchange.read_tiff(fname_data)
    nprj, px,  _ = data.shape
    data = nor_phase(data)
```
    
```
    abs_ratio_all = np.arange(0.01, 0.1, 0.01)
    for i, abs_ratio in enumerate(abs_ratio_all):
        gan_phase_object = GANphase(data[i], energy, z, pv, 
```
        
   1. Since I have a different set up with the tiff files, I want to clarify somethings. Is the `data_spider.tif` a 3d stack of images?
   1.1. If yes, then i'm confused if `dxchange.read_tiff` can return a 3d image
   1.1.1. does it mean that you're training the model for 10 images through `data[i]` 
   1.2. If no, then what is `data[i]` doing, unless it's reading the rows of the image?
   
   2. The spider data has some problems for me, as there I need to either use some **cropping or filtering**. How did you handle this problem? 
   
   3. It says there are 2000 _iterations_, is that correct? just to confirm. Because that would mean this code is doing 20,000 iterations in total.

**Comment by XYangXRay** [comment]
Hi @daveabiy ,
1. data_spider.tif is a 3d stack. dxchange.read_tiff can read 3d stack if it is a single file. Here is my test for different absorption ratios. Please change the iteration if you need to do phase retrieval for multiple angles. 
2. I am not sure what the original data looks like. I will share the data that I did the test. 
3. 2000 iteration is for the test. It would be big difference from 1000 to 2000.
